.caching_rust: &caching_rust
  cache:
    paths:
      - .cargo/
      - .cache/sccache
      - target/x86_64-unknown-linux-musl/release/material

stages:
  - deploy

pages:
  stage: deploy
  image: rust
  <<: *caching_rust
  before_script:
    - export CARGO_HOME="${PWD}/.cargo"
    - export SCCACHE_DIR="${PWD}/.cache/sccache"
    - export PATH="$CI_PROJECT_DIR/.cargo/bin:$PATH"
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - .cargo/
      - .cache/sccache
