pages:
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  cache:
    paths:
      - .cargo/
      - .cargo/bin/
      - $CARGO_HOME/
  before_script:
    - export CARGO_HOME="$CARGO_HOME"
    - export PATH="$CARGO_HOME/bin:$PATH"
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
