stages:
  - scanning
  - documentation
  - build
  - release
  - deploy
  - loadtest

pages:
  stage: documentation
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo/bin
  before_script:
    - export PATH="$CARGO_HOME:$PATH"
    - mkdir -p $CARGO_HOME
    - $CARGO_HOME/mdbook --version || curl -SSL https://api.github.com/repos/rust-lang/mdbook/releases | grep "browser_download_url" | grep 'x86_64-unknown-linux-gnu[.]tar.gz' | head -n 1 | grep -Eo 'https://[^\"]*' | xargs wget -O - | tar -xz --directory=$CARGO_HOME
  script:
    - $CARGO_HOME/mdbook build -d public
  artifacts:
    paths:
      - public
