stages:
  - deploy

pages:
  stage: deploy
  image: rust
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - echo $PATH
    - echo $CARGO_HOME
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - $CARGO_HOME/bin/
