pages:
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo/bin/
  before_script:
    - export PATH="$CARGO_HOME:$PATH"
    - mkdir -p $CARGO_HOME
    - $CARGO_HOMEmdbook --version || curl -s https://api.github.com/repos/atom/atom/releases | grep browser_download_url | grep 'x86_64-unknown-linux-gnu[.]tar.gz' | head -n 1 | cut -d '"' -f 4 | tar -xz --directory=$CARGO_HOME
  script:
    - $CARGO_HOMEmdbook build -d public
  cache:
    key:
      - $(curl -s https://api.github.com/repos/rust-lang/mdbook/releases/latest | grep 'browser_download_url.*tar.gz' | grep 'x86_64-unknown-linux-gnu[.]tar.gz' | cut -d : -f 2,3 | tr -d \" | cut -d'/' -f8)
    paths:
      - $CARGO_HOME/
  artifacts:
    paths:
      - public
