.caching_rust: &caching_rust
  cache:
    paths:
      - .cargo/
      - .cache/sccache
      - .cargo/bin/mdbook
      - .cargo/bin/

stages:
  - deploy

pages:
  stage: deploy
  image: hatembt/rust-ci:latest
  <<: *caching_rust
  before_script:
    - export CARGO_HOME="${PWD}/.cargo"
    - export SCCACHE_DIR="${PWD}/.cache/sccache"
    - export PATH="$CI_PROJECT_DIR/.cargo/bin:$PATH"
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  artifacts:
    paths:
      - public
  cache:
    key: $CI_JOB_NAME
    paths:
      - .cargo/
      - .cache/sccache
